version: "3.7"
services:
  app:
    build:
      args:
        user: diawara
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: babaata
    container_name: babaata-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - babaata

  db:
    build:
      args:
        user: diawara
        uid: 1000
      context: ./docker-compose/mysql
      dockerfile: Dockerfile
    # image: postgres:10.1
    image: mysql:5.7
    container_name: babaata-db
    restart: unless-stopped
    environment:
      # if mysql choosed
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      # DB_ROOT_PASS: ${DB_PASSWORD}
      # if postgresql choosed
      # POSTGRES_DB: ${DB_DATABASE}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_PORT: ${DB_PORT}
      SERVICE_TAGS: dev
      # SERVICE_NAME: postgres
      SERVICE_NAME: mysql
    volumes:
      # if postgresql choosed
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      # if mysql choosed 
      # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
      # - 3306:3306
    networks:
      - babaata

  nginx:
    image: nginx:alpine
    container_name: babaata-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - babaata

networks:
  babaata:
    driver: bridge
